version: '3'

services:

  backend:
    env_file: .env.testing
    environment:
      POSTGRES_DB_PASSWORD: "${POSTGRES_DB_PASSWORD}"
      MAILCHIMP_API_KEY: "${MAILCHIMP_API_KEY}"
      CLIENT_DOMAIN: "https://www.mowo.space/"


  db:
    env_file: .env.testing
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_DB_PASSWORD}"
      
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        BASE_URL: "http://backend:8000"
        BASE_SERVER_URL: "https://www.mowo.space"

  nginx:
    ports:
      - "443:443"
    volumes:
      - ./nginx/production:/etc/nginx/conf.d
