version: '3'

services:

  backend:
    env_file: .env.production
    environment:
      POSTGRES_DB_PASSWORD: "${POSTGRES_DB_PASSWORD}"
      MAILCHIMP_API_KEY: "${MAILCHIMP_API_KEY}"
      AWS_STORAGE_BUCKET_NAME: "mowo-production"
      CLIENT_DOMAIN: "https://www.mowo.space/"
      PIPEDRIVE_URL: "https://mowospaces.pipedrive.com/api/v1/"

  db:
    env_file: .env.production
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_DB_PASSWORD}"
      
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        BASE_URL: "http://backend:8000"
        BASE_SERVER_URL: "https://www.mowo.space"
        STRIPE_PUBLISHABLE_KEY: "pk_live_51I47k4IpxsSLqlNand4pmbwnCQd7Z9uARgt0NHEKdOZImSk3ZDPVq2bqDf5z7woQdemJNCMTdpjLsKHX8ffz8swz00JNgiWqSA"

  nginx:
    ports:
      - "443:443"
    volumes:
      - ./nginx/production:/etc/nginx/conf.d
