version: '3'

volumes:
  pgdata:

services:
  backend:
    build: ./backend
    environment:
      POSTGRES_DB_NAME: postgres
      POSTGRES_DB_USER: postgres
      POSTGRES_DB_PASSWORD: postgres
      POSTGRES_DB_HOST: db
      POSTGRES_DB_PORT: 5432
    volumes:
      - .:/backend
    expose:
      - "8000"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # expose:
    #   - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend

  web:
    build: ./web
    ports:
      - "80:3000"
