version: '3'

services:

  backend:
    env_file: .env.dev
    environment:
      POSTGRES_DB_PASSWORD: "${POSTGRES_DB_PASSWORD}"
      MAILCHIMP_API_KEY: "${MAILCHIMP_API_KEY}"
      AWS_STORAGE_BUCKET_NAME: "mowo-dev"
      CLIENT_DOMAIN: "https://dev.mowo.space/"
      PIPEDRIVE_URL: "https://mowospaces.pipedrive.com/api/v1/"

  db:
    env_file: .env.dev
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_DB_PASSWORD}"
      
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        BASE_URL: "https://testing.mowo.space"
        BASE_SERVER_URL: "https://testing.mowo.space"

  nginx:
    ports:
      - "443:443"
    volumes:
      - ./nginx/dev:/etc/nginx/conf.d
