version: '3'

services:
      
  web:
    environment:
      # Set an env in container for constants.js
      BASE_SERVER_URL: "https://dev.mowo.space"
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        # Set as env during image building for next.config.js
        BASE_URL: "http://backend:8000"
        BASE_SERVER_URL: "https://dev.mowo.space"

  nginx:
    build:
      context: ./nginx/docker/dev
      dockerfile: Dockerfile
